=== magiclud/XML_DTD_XSD/books.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (author+, title, introduction, chapter+)>

<!ELEMENT author (#PCDATA)>
									<!ATTLIST author country CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT introduction (#PCDATA)>
<!ELEMENT chapter title CDATA (nrPage, section+)>
<!ELEMENT nrPage (#PCDATA)>
<!ELEMENT section (title, nrParagraph*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT nrParagraph (#PCDATA)>

=== magiclud/XML_DTD_XSD/books.xml
<?xml version="1.0"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books>
  <book>
	<!-- co ze sprawa gdy jest wiecej autorow?  -->
    <author>Mario Puzo</author>
    <title>The Godfather</title>
	<introduction>Za siedmioma lasami, za siedmioma wzgórzami...</introduction>
	<chapter title="Zamek">
		<nrPage>12</nrPage>
		<section>
			<title>Czerwona komnata</title>
			<nrParagraph>3</nrParagraph>
		</section>
		<section>
			<title>Uczta na zamku</title>
			<nrParagraph>0</nrParagraph>
		</section>
	<chapter>
	<chapter title="Polowanie">
		<nrPage>12</nrPage>
		<section>
			<title>Atak niedzwiedzia</title>
			<nrParagraph>4</nrParagraph>
		</section>
		<section>
			<title>Spór Asesora z Rejentem</title>
			<nrParagraph>3</nrParagraph>
		</section>
	<chapter>
  </book>
  <book>
    <author>Szymborska Wisława</author>
    <title>Wiersze wybrane</title>
  </book>
</books>
